### ISSUE TITLE
Reworking the threshold diagram 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#39]
Goal : This diagram is not understood but has good data in there 

Owner : Laura 
Design lead : @sabrinang 
Interested : @APLSmith @thisandagain @secretrobotron

**Comment by LauraReynal** [comment]
![webjourney v2 chicago](https://cloud.githubusercontent.com/assets/8261945/7361233/c6f79752-ed1a-11e4-83de-53c1fbe2bc9c.jpg)

**Comment by LauraReynal** [comment]
@sabrinang I'd like to consolidate "Unaware" and "unaware but no use" into a bigger one. As we did for creation and limited use. I will make update to the copy document. What do you think ?

**Comment by LauraReynal** [comment]
![teenagers threshold - chicago](https://cloud.githubusercontent.com/assets/8261945/7361287/68cdb3f4-ed1b-11e4-88cd-898c3c34362f.jpg)

**Comment by LauraReynal** [comment]
![educators threshold chicago](https://cloud.githubusercontent.com/assets/8261945/7361297/7d80df1a-ed1b-11e4-8600-f3c434372fae.jpg)

**Comment by LauraReynal** [comment]
I am guessing a Copy document will be useful - Im on it for this week

**Comment by sabrinang** [comment]
I made a sketch of organizing this diagram data:

![threshold-format-brainstorm](https://cloud.githubusercontent.com/assets/2492510/7420847/c607c3fa-ef34-11e4-9bf4-16583e087f0b.png)
I know the copy still needs to be collected and finalized but from the sketches made in Chicago I've been playing around with the format so far. I tried simplifying the threshold into larger groups and that it goes from non-user to user as the reader goes down (progresses one way) the page instead of inward (progresses two ways) indicated with the arrows on the sketch. I think some of the confusion is that they don't know which way to read the diagram or that they are confused why the non-user groups are split this way visually which we can solve by having different types of non-users within the same visual section.

@LauraReynal Let me know what you think and when you have the copy (I know you still want quotes included)

**Comment by LauraReynal** [comment]
Thanks @sabrinang I love your new approach on the right. I think it does simplify things to have just one way of reading it, from top to bottom.
I would just stick to one title for zone 2 : "Ambivalence" and zone 3 "Embrace"
Let me send you the copy  so we could see how it looks with all the information. 
Thanks !

cc / @thisandagain does this approach seem better for you as well ?

**Comment by LauraReynal** [comment]
Hey @sabrinang The copy for the teenagers is ready here https://docs.google.com/document/d/1vbq0Ve73LYOpVHdklRM85Z3QPcBmqBUpeMA0D7Jpoy4/edit

**Comment by LauraReynal** [comment]
@lovegushwa the copy is done for both the teenagers and the educators
You can find the doc here https://docs.google.com/document/d/1vbq0Ve73LYOpVHdklRM85Z3QPcBmqBUpeMA0D7Jpoy4/edit?usp=sharing

@secretrobotron @thisandagain Wanna have a look and do a quick copy review ?

**Comment by secretrobotron** [comment]
:+1: done. Left a few comments.
btw, I love @sabrinang's new design. Much easier to read and digest.
