### ISSUE TITLE
find a domain name for our research website

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#98]
@secretrobotron @KevZawacki @HPaulJohnson @edrushka @benrito @simonwex 

We need to come up with a domain name for the research website! Throw your ideas in here :-) :smile_cat: :fire: :boat: :whale: 

Research.mozilla.org is already taken

**Comment by LauraReynal** [comment]
- Studying the Global Web
globalweb.org 

- Mozillafoundation.org/ research

**Comment by secretrobotron** [comment]
https://www.mozilla.org/en-US/foundation/research

**Comment by benrito** [comment]
+1 bob

**Comment by LauraReynal** [comment]
Mozilla Research Lab 

Mozillaresearchlab.org

**Comment by secretrobotron** [comment]
mozilla.org/foundation/research

**Comment by LauraReynal** [comment]
:+1:

**Comment by secretrobotron** [comment]
discoveringtheglobalweb.org -->> mozilla.org/foundation/research

**Comment by benrito** [comment]
I wouldn't introduce any branding now, just focus on making it part of mozilla.org

**Comment by secretrobotron** [comment]
:+1: you just settled the argument we were having in realtime.

**Comment by LauraReynal** [comment]
:+1:

**Comment by secretrobotron** [comment]
@simonwex @jbuck can we get mozilla.org/foundation/research?

**Comment by secretrobotron** [comment]
and by "get", i mean "put a new website there"

**Comment by jbuck** [comment]
You can file PRs against https://github.com/mozilla/bedrock to land stuff there, but I don't think you'd be able to create a new website that lives at that subpath

**Comment by edrushka** [comment]
Just want to flag that MoCo is re-doing the entire mozilla.org site next year ([old deck] (https://docs.google.com/presentation/d/1UR8cs6NUxkdEjZ-R3LGPWItgGtV-IjoE4RICrHirFhc/edit?pli=1#slide=id.g8c9d10f4a_013)). Also, getting changes to Mozilla.org/foundation is sloooooow ([this ticket] (https://github.com/MozillaFoundation/plan/issues/378) filed in March and still not complete).

**Comment by edrushka** [comment]
Feel like I might be going against the grain here, but to me the word "research" doesn't capture the full essence of the work. I might go with a verb like "listening" that's more evocative, friendly and interesting. "Research" feels dry and boring.

**Comment by secretrobotron** [comment]
@edrushka noted. More ideas welcome :/.

**Comment by edrushka** [comment]
Witness?

**Comment by secretrobotron** [comment]
@davidascher any thoughts/insights?

**Comment by LauraReynal** [comment]
@cassiemc @kristinashu

**Comment by cassiemc** [comment]
This is a little longwinded, sorry. 

The straightforward nature of 'research' will be easier to remember in the url, it's more standard and I prefer it. We can get clever on the page copy, imo.

I'd suspect the final url won't be decided until we figure out how the new strategy or plans for the foundation site and research efforts evolve, so I wonder if in the interim if there is any harm in having it live at build.webmaker.com/research. I realize the work is wider than webmaker, but we could then change all those urls (like build/design) over to foundation or whatever the future url is in one fell swoop (and delete what's no longer relevant). One reason for this is to prevent stalling on the UI of this page, since the URL will determine the brand attributes to a large extent. Any other url that is external to mozilla.com could solve this.

@kristinashu has made excellent progress so far on a fresh, simple UI that feels like an evolution of both mozilla and MLN. It focuses on the research content itself with a lovely emphasis on the people captured in @LauraReynal's photography. I think we should go with it. It's unknown atm where Mozilla is going with the overarching brand and if we have to get it through moco for brand approval b/c of the url that will slow things down. Which seems contrary to the immediate goal of having a single page that points to all the research reports.

**Comment by davidascher** [comment]
I agree with Cassie but would go further. Whatever.org is fine for now, the
point as I understand it is to just get stuff out, and not try and
establish permanent home yet (esp because of the fuzziness around all our
domains right now). We're not trying to get accidental traffic. I would
focus on a workflow that is lightweight, so that we can spend more time
doing research and less time building websites.

Also agree with Lynn that research isn't the right word for the public,
especially given the meaning of that word in MoCo today (and on Google
under "Mozilla research").

**Comment by secretrobotron** [comment]
That's great. build.webmaker.org/research is where we can start at least.

@LauraReynal, sound ok to you? We can revisit once strategy/domains discussion has progressed.

**Comment by LauraReynal** [comment]
:+1: :bow: thanks everyone ! Let's do this

**Comment by cassiemc** [comment]
Great! Closing. Final (temporary) domain is build.webmaker.org/research
